name: scFAN
path: models

model:
  emb_size: 6    
  linear_size: [160, 240, 240] 
  full_size: [15360 ,919] 
  dropouts: [0.2, 0.5]
  DNA_pad: 10

padding:
  target_len: 200
  DNA_len: 1024
  DNA_pad: 10
  tf_len: 20

  DNA_N: False

train:
  batch_size: 64
  num_epochs: 5
  opt_params:
    weight_decay: 5e-07
    optimizer_cls: Adam
    lr: 0.001

valid:
  batch_size: 64

test:
  batch_size: 64
  
classweights: True