name: SimpleCNN
path: models

model:
  emb_size: 6
  conv_size: [5, 9, 13, 17, 21]
  conv_num: [64, 64, 64, 64, 64]
  conv_off: [8, 6, 4, 2, 0]
  dropout: 0.25
  linear_size: [128, 512]
  full_size: [512, 128] # for simple cnn
  DNA_pad: 10

padding:
  target_len: 256
  DNA_len: 1024
  DNA_pad: 10
  tf_len: 39
  DNA_N: True

train:
  batch_size: 64
  num_epochs: 10000  
  opt_params:
    #optimizer_cls: Adadelta
    #lr: 0.05
    weight_decay: 1e-4
    optimizer_cls: Adam
    lr: 0.001

valid:
  batch_size: 64

test:
  batch_size: 64
  
classweights: True