name: SimpleCNN_2d
path: models

model:
  emb_size: 7 # depending on number of bw 
  conv_size: [5, 9, 13, 17, 21]
  conv_num: [64, 128, 256, 512, 1024]
  conv_off: [8, 6, 4, 2, 0]
  dropout: 0.25
  #linear_size: [256, 288, 323, 363, 407, 512]
  linear_size: [160,240,480]

  full_size: [4096 ,2048] # for simple cnn
  DNA_pad: 10

padding:
  target_len: 200
  DNA_len: 1024
  DNA_pad: 10
  tf_len: 39
  DNA_N: True

train:
  batch_size: 64
  num_epochs: 100
  opt_params:
    #optimizer_cls: Adadelta
    #lr: 0.05
    weight_decay: 1e-4
    optimizer_cls: Adam
    lr: 0.001

valid:
  batch_size: 64

test:
  batch_size: 64
  
classweights: True