name: SimpleCNN
path: models

model:
  emb_size: 6
  conv_size: [5, 9, 13, 17, 21]
  conv_num: [16, 16, 16, 16, 16]
  conv_off: [8, 6, 4, 2, 0]
  dropout: 0.25
  linear_size: [128, 512]
  full_size: [2048] # for simple cnn
  DNA_pad: 10

padding:
  DNA_len: 1024
  DNA_pad: 10
  tf_len: 39

train:
  batch_size: 64
  num_epochs: 100  
  opt_params:
    #optimizer_cls: Adadelta
    #lr: 0.05
    weight_decay: 1e-5
    optimizer_cls: Adam
    lr: 0.0001

valid:
  batch_size: 64

test:
  batch_size: 64
  
classweights: True