name: TFNet
path: models

model:
  emb_size: 6
  conv_size: [5, 9, 13, 17, 21]
  conv_num: [16, 16, 16, 16, 16]
  conv_off: [8, 6, 4, 2, 0]
  dropout: 0.25
  linear_size: [32, 16]
  full_size: [1856, 256,64] # the frist size should be [linear_size[-1] * len(all_tfs) * 1024(DNA_len + 2*DNA_pad - conv_off - 2 * conv_size + 1) / 4**len(self.max_pool) ]; 1856 for 4 maxpooling, 7424 for 3
  DNA_pad: 10

padding:
  DNA_len: 1024
  DNA_pad: 10
  tf_len: 39

train:
  batch_size: 32
  num_epochs: 20
  opt_params:
    optimizer_cls: Adadelta
    lr: 0.01
    weight_decay: 1e-4

valid:
  batch_size: 32

test:
  batch_size: 32
