name: TFNet
path: models

model:
  emb_size: 6
  conv_size: [5, 9, 13, 17, 21]
  conv_num: [128, 128, 128, 128, 128]
  conv_off: [8, 6, 4, 2, 0]
  dropout: 0.25
  linear_size: [128, 16]
  full_size: [29696, 128] # the frist size should be [linear_size[-1] * len(all_tfs) * 1024(DNA_len + 2*DNA_pad - conv_off - 2 * conv_size + 1) / 4 * 4 for two maxpool]
  DNA_pad: 10

padding:
  target_len: 200
  DNA_len: 1024
  DNA_pad: 10
  tf_len: 39
  DNA_N: True

train:
  batch_size: 64
  num_epochs: 5
  opt_params:
    #optimizer_cls: Adadelta
    #lr: 0.01
    weight_decay: 1e-4
    optimizer_cls: Adam
    lr: 0.001


valid:
  batch_size: 64

test:
  batch_size: 64

classweights: True