name: TFNet
path: models

model:
  emb_size: 6 # depending on number of bw       # for simplecnn_2d
  linear_size: [320] # kernel size 26 and maxpool size 13 result in 320 feature len
  #linear_size: [160, 240, 480] # kernel size 8 and maxpool size 4 result in 54 feature len
  full_size: [48640 ,695] # for deepsea
  #full_size:[51840, 1024]
  dropouts: [0.2, 0.5]
  DNA_pad: 10

padding:
  target_len: 200
  DNA_len: 1024
  DNA_pad: 10
  tf_len: 20

  DNA_N: False

train:
  batch_size: 64
  num_epochs: 5
  opt_params:
    #optimizer_cls: Adadelta
    #lr: 0.05
    weight_decay: 5e-07
    optimizer_cls: Adam
    lr: 0.001

valid:
  batch_size: 64

test:
  batch_size: 64
  
classweights: True